# Generated by Django 5.2.8 on 2025-12-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopifyAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(help_text='Nombre de la tienda (ej: altamachines)', max_length=255, unique=True)),
                ('client_id', models.CharField(help_text='Client ID de la app', max_length=255)),
                ('client_secret', models.CharField(help_text='Client Secret de la app', max_length=255)),
                ('access_token', models.CharField(help_text='Access Token actual', max_length=255)),
                ('scopes', models.TextField(blank=True, help_text='Scopes otorgados')),
                ('expires_at', models.DateTimeField(help_text='Fecha y hora de expiración')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Si esta tienda está activa')),
            ],
            options={
                'verbose_name': 'Shopify Access Token',
                'verbose_name_plural': 'Shopify Access Tokens',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifySyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('products', 'Productos'), ('orders', 'Órdenes'), ('token_refresh', 'Renovación de Token')], max_length=50)),
                ('status', models.CharField(choices=[('success', 'Exitoso'), ('error', 'Error'), ('partial', 'Parcial')], max_length=50)),
                ('items_processed', models.IntegerField(default=0)),
                ('items_created', models.IntegerField(default=0)),
                ('items_updated', models.IntegerField(default=0)),
                ('items_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ShopifyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(help_text='ID de la orden en Shopify', unique=True)),
                ('order_number', models.IntegerField(help_text='Número de orden visible')),
                ('name', models.CharField(help_text='Nombre de la orden (ej: #1001)', max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_first_name', models.CharField(blank=True, max_length=255)),
                ('customer_last_name', models.CharField(blank=True, max_length=255)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='PYG', max_length=3)),
                ('financial_status', models.CharField(choices=[('pending', 'Pendiente'), ('authorized', 'Autorizado'), ('partially_paid', 'Parcialmente Pagado'), ('paid', 'Pagado'), ('partially_refunded', 'Parcialmente Reembolsado'), ('refunded', 'Reembolsado'), ('voided', 'Anulado')], default='pending', max_length=50)),
                ('fulfillment_status', models.CharField(blank=True, choices=[(None, 'Sin Enviar'), ('fulfilled', 'Enviado'), ('partial', 'Parcial'), ('restocked', 'Reabastecido')], max_length=50, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('created_at_shopify', models.DateTimeField()),
                ('updated_at_shopify', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Orden de Shopify',
                'verbose_name_plural': 'Órdenes de Shopify',
                'ordering': ['-created_at_shopify'],
                'indexes': [models.Index(fields=['shopify_id'], name='am_shopify__shopify_11e6df_idx'), models.Index(fields=['order_number'], name='am_shopify__order_n_b4c2aa_idx'), models.Index(fields=['financial_status'], name='am_shopify__financi_984197_idx'), models.Index(fields=['customer_email'], name='am_shopify__custome_60b3a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShopifyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(help_text='ID del producto en Shopify', unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('product_type', models.CharField(blank=True, max_length=255)),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(default='active', help_text='active, draft, archived', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('inventory_quantity', models.IntegerField(default=0)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('barcode', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at_shopify', models.DateTimeField(blank=True, null=True)),
                ('updated_at_shopify', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Producto de Shopify',
                'verbose_name_plural': 'Productos de Shopify',
                'ordering': ['-updated_at_shopify'],
                'indexes': [models.Index(fields=['shopify_id'], name='am_shopify__shopify_ab10ce_idx'), models.Index(fields=['sku'], name='am_shopify__sku_acee09_idx'), models.Index(fields=['barcode'], name='am_shopify__barcode_cb8f8a_idx'), models.Index(fields=['handle'], name='am_shopify__handle_71d781_idx')],
            },
        ),
    ]
