# Generated by Django 5.2.8 on 2025-12-13 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0079_alter_clientes_pdv_type_business'),
        ('am_shopify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='converted_to_invoice',
            field=models.BooleanField(default=False, help_text='Si la orden ya fue convertida a factura SIFEN'),
        ),
        migrations.AddField(
            model_name='shopifyorder',
            name='document_header',
            field=models.ForeignKey(blank=True, help_text='Factura SIFEN generada desde esta orden', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_orders', to='Sifen.documentheader'),
        ),
    ]
