# Generated by Django 5.2.8 on 2025-12-15 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0079_alter_clientes_pdv_type_business'),
        ('am_shopify', '0002_shopifyorder_converted_to_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysynclog',
            name='sync_type',
            field=models.CharField(choices=[('products', 'Productos'), ('orders', 'Órdenes'), ('payments', 'Pagos'), ('token_refresh', 'Renovación de Token')], max_length=50),
        ),
        migrations.CreateModel(
            name='ShopifyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.BigIntegerField(help_text='ID de la orden en Shopify', unique=True)),
                ('order_number', models.IntegerField(help_text='Número de orden visible (#1001)')),
                ('order_name', models.CharField(help_text='Nombre de la orden (ej: #1001)', max_length=50)),
                ('customer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, help_text='Nombre completo del cliente', max_length=500, null=True)),
                ('is_innominado', models.BooleanField(default=False, help_text='True si el cliente es innominado (sin datos)')),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total de la orden', max_digits=15)),
                ('subtotal_price', models.DecimalField(decimal_places=2, help_text='Subtotal sin impuestos', max_digits=15)),
                ('total_tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency', models.CharField(default='PYG', max_length=3)),
                ('payment_gateway', models.CharField(blank=True, help_text='Gateway de pago usado', max_length=255)),
                ('payment_method', models.CharField(default='cash', help_text='Método de pago (cash, card, etc)', max_length=100)),
                ('financial_status', models.CharField(default='paid', max_length=50)),
                ('line_items', models.JSONField(default=list, help_text='Productos de la orden')),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('billing_address', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('order_created_at', models.DateTimeField(help_text='Fecha de creación en Shopify')),
                ('order_processed_at', models.DateTimeField(blank=True, null=True)),
                ('conversion_status', models.CharField(choices=[('pending', 'Pendiente'), ('converted', 'Convertido'), ('error', 'Error'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('conversion_error', models.TextField(blank=True, help_text='Mensaje de error si falló la conversión')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_header', models.ForeignKey(blank=True, help_text='Factura SIFEN generada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopify_payments', to='Sifen.documentheader')),
            ],
            options={
                'verbose_name': 'Pago de Shopify',
                'verbose_name_plural': 'Pagos de Shopify',
                'ordering': ['-order_created_at'],
                'indexes': [models.Index(fields=['shopify_order_id'], name='am_shopify__shopify_d60525_idx'), models.Index(fields=['order_number'], name='am_shopify__order_n_2833d1_idx'), models.Index(fields=['conversion_status'], name='am_shopify__convers_95290f_idx'), models.Index(fields=['customer_email'], name='am_shopify__custome_b5f38c_idx')],
            },
        ),
    ]
