# Generated by Django 5.2.8 on 2025-12-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_shopify', '0003_shopify_payment_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifysynclog',
            name='sync_type',
            field=models.CharField(choices=[('products', 'Productos'), ('orders', 'Órdenes'), ('payments', 'Pagos'), ('customers', 'Clientes'), ('token_refresh', 'Renovación de Token')], max_length=50),
        ),
        migrations.CreateModel(
            name='ShopifyCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_id', models.BigIntegerField(help_text='ID del cliente en Shopify', unique=True)),
                ('admin_graphql_api_id', models.CharField(blank=True, help_text='ID de GraphQL Admin API', max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(choices=[('disabled', 'Deshabilitado'), ('invited', 'Invitado'), ('enabled', 'Habilitado'), ('declined', 'Rechazado')], default='disabled', max_length=50)),
                ('verified_email', models.BooleanField(default=False, help_text='Si el email fue verificado')),
                ('orders_count', models.IntegerField(default=0, help_text='Número de órdenes realizadas')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, help_text='Total gastado', max_digits=15)),
                ('currency', models.CharField(default='PYG', help_text='Moneda del cliente', max_length=3)),
                ('last_order_id', models.BigIntegerField(blank=True, help_text='ID de la última orden', null=True)),
                ('last_order_name', models.CharField(blank=True, help_text='Nombre de la última orden (ej: #1025)', max_length=50)),
                ('note', models.TextField(blank=True, help_text='Notas del cliente', null=True)),
                ('tags', models.CharField(blank=True, help_text='Etiquetas del cliente', max_length=500)),
                ('tax_exempt', models.BooleanField(default=False, help_text='Si está exento de impuestos')),
                ('tax_exemptions', models.JSONField(blank=True, default=list, help_text='Lista de exenciones de impuestos')),
                ('email_marketing_consent_state', models.CharField(blank=True, help_text='Estado de consentimiento de email marketing', max_length=50)),
                ('email_marketing_consent_opt_in_level', models.CharField(blank=True, help_text='Nivel de opt-in de email', max_length=50)),
                ('email_marketing_consent_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sms_marketing_consent_state', models.CharField(blank=True, help_text='Estado de consentimiento de SMS marketing', max_length=50)),
                ('sms_marketing_consent_opt_in_level', models.CharField(blank=True, help_text='Nivel de opt-in de SMS', max_length=50)),
                ('sms_marketing_consent_updated_at', models.DateTimeField(blank=True, null=True)),
                ('sms_marketing_consent_source', models.CharField(blank=True, help_text='Fuente del consentimiento SMS', max_length=100)),
                ('multipass_identifier', models.CharField(blank=True, help_text='Identificador de Multipass', max_length=255, null=True)),
                ('addresses', models.JSONField(blank=True, default=list, help_text='Lista de todas las direcciones')),
                ('default_address', models.JSONField(blank=True, default=dict, help_text='Dirección por defecto')),
                ('default_address_id', models.BigIntegerField(blank=True, null=True)),
                ('default_address_first_name', models.CharField(blank=True, max_length=255)),
                ('default_address_last_name', models.CharField(blank=True, max_length=255)),
                ('default_address_company', models.CharField(blank=True, max_length=255)),
                ('default_address_address1', models.CharField(blank=True, max_length=500)),
                ('default_address_address2', models.CharField(blank=True, max_length=500)),
                ('default_address_city', models.CharField(blank=True, max_length=255)),
                ('default_address_province', models.CharField(blank=True, max_length=255)),
                ('default_address_province_code', models.CharField(blank=True, max_length=10)),
                ('default_address_country', models.CharField(blank=True, max_length=255)),
                ('default_address_country_code', models.CharField(blank=True, max_length=10)),
                ('default_address_country_name', models.CharField(blank=True, max_length=255)),
                ('default_address_zip', models.CharField(blank=True, max_length=50)),
                ('default_address_phone', models.CharField(blank=True, max_length=50)),
                ('created_at_shopify', models.DateTimeField(blank=True, help_text='Fecha de creación en Shopify', null=True)),
                ('updated_at_shopify', models.DateTimeField(blank=True, help_text='Fecha de actualización en Shopify', null=True)),
                ('synced_at', models.DateTimeField(auto_now=True, help_text='Última sincronización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente de Shopify',
                'verbose_name_plural': 'Clientes de Shopify',
                'ordering': ['-updated_at_shopify'],
                'indexes': [models.Index(fields=['shopify_id'], name='am_shopify__shopify_2ecffa_idx'), models.Index(fields=['email'], name='am_shopify__email_1a4cf0_idx'), models.Index(fields=['phone'], name='am_shopify__phone_7c2c48_idx'), models.Index(fields=['state'], name='am_shopify__state_cca403_idx'), models.Index(fields=['last_order_id'], name='am_shopify__last_or_705315_idx')],
            },
        ),
    ]
