# Generated by Django 5.2.8 on 2025-12-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_shopify', '0004_add_shopify_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycustomer',
            name='email',
            field=models.CharField(blank=True, help_text='Email del cliente', max_length=255, null=True),
        ),
    ]
