# Generated by Django 5.2.8 on 2025-12-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_shopify', '0005_fix_email_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_address1',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_address2',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_company',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_country',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_country_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_country_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_phone',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_province',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_province_code',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shopifycustomer',
            name='default_address_zip',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
