# Generated by Django 5.2.8 on 2025-12-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_shopify', '0006_fix_address_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifyorder',
            name='customer_tags',
            field=models.CharField(blank=True, help_text='Tags del cliente (contiene RUC)', max_length=500),
        ),
        migrations.AddField(
            model_name='shopifypayment',
            name='customer_tags',
            field=models.CharField(blank=True, help_text='Tags del cliente (contiene RUC)', max_length=500),
        ),
    ]
