# Generated by Django 5.2.8 on 2025-12-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('am_shopify', '0007_add_customer_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifypayment',
            name='total_shipping',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de envío', max_digits=15),
        ),
    ]
