# Generated by Django 5.2.8 on 2026-01-04 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sifen', '0083_add_anclaje_cliente_to_clientes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta de Crédito/Débito'), ('otro', 'Otro')], default='efectivo', max_length=20, verbose_name='Método de Pago')),
                ('numero_referencia', models.CharField(blank=True, help_text='Número de cheque, transferencia, etc.', max_length=100, null=True, verbose_name='Número de Referencia')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('cargado_fecha', models.DateTimeField(auto_now_add=True)),
                ('cargado_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_cargados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('documentheaderobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='Sifen.documentheader', verbose_name='Factura')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago', '-cargado_fecha'],
            },
        ),
    ]
