# Generated by Django 3.2.22 on 2024-07-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0002_documentdetail_documentheader'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='actualizado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='actualizado_usuario',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='anulado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='anulado_usuario',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='source',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
