# Generated by Django 3.2.22 on 2024-07-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadeconomica',
            name='codigo_actividad',
            field=models.CharField(max_length=120),
        ),
    ]
