# Generated by Django 3.2.22 on 2024-07-30 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0006_alter_actividadeconomica_codigo_actividad'),
    ]

    operations = [
        migrations.AddField(
            model_name='etimbrado',
            name='serie',
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
