# Generated by Django 3.2.22 on 2024-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0007_etimbrado_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etimbrado',
            name='establecimiento',
        ),
        migrations.AddField(
            model_name='eexpedicion',
            name='establecimiento',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etimbrado',
            name='vigencia',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
