# Generated by Django 3.2.22 on 2024-07-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0008_auto_20240730_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etimbrado',
            name='vigencia',
        ),
    ]
