# Generated by Django 3.2.22 on 2024-07-30 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0009_remove_etimbrado_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enumbers',
            name='expd',
        ),
        migrations.RemoveField(
            model_name='enumbers',
            name='timbradoobj',
        ),
        migrations.AddField(
            model_name='enumbers',
            name='expobj',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Sifen.eexpedicion'),
            preserve_default=False,
        ),
    ]
