# Generated by Django 3.2.22 on 2024-07-30 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0010_auto_20240730_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eexpedicion',
            name='numero',
        ),
    ]
