# Generated by Django 3.2.22 on 2024-07-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0011_remove_eexpedicion_numero'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Eexpedicion',
            new_name='Eestablecimiento',
        ),
    ]
