# Generated by Django 3.2.22 on 2024-07-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0012_rename_eexpedicion_eestablecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='eestablecimiento',
            name='expedicion',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
    ]
