# Generated by Django 3.2.22 on 2024-07-30 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0013_eestablecimiento_expedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_g5',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=19),
            preserve_default=False,
        ),
    ]
