# Generated by Django 3.2.22 on 2024-07-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0014_documentheader_doc_g5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='doc_numero',
            field=models.BigIntegerField(null=True),
        ),
    ]
