# Generated by Django 3.2.22 on 2024-07-31 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0015_alter_documentheader_doc_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='ek_cod_seg',
            field=models.CharField(default='0', max_length=9),
        ),
    ]
