# Generated by Django 3.2.22 on 2024-07-31 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0016_alter_documentheader_ek_cod_seg'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_tipo_cod',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='doc_tipo_desc',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
