# Generated by Django 3.2.22 on 2024-07-31 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0017_auto_20240731_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='actualizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='actualizado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='actualizado_usuario',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='anulado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='anulado_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='anulado_usuario',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
