# Generated by Django 3.2.22 on 2024-07-31 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0018_auto_20240731_0402'),
    ]

    operations = [
        # CSeg con managed=False fue eliminado de 0001_initial.py
        # Esta operación ya no es necesaria
    ]
