# Generated by Django 3.2.22 on 2024-07-31 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0020_delete_cseg'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_seguridad', models.CharField(max_length=100)),
                ('asignado_model', models.CharField(default='ND', max_length=15)),
                ('asignado_doc', models.BigIntegerField(default=0)),
            ],
        ),
    ]
