# Generated by Django 3.2.22 on 2024-07-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0021_cseg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='doc_tipo_desc',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
