# Generated by Django 3.2.22 on 2024-07-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0022_alter_documentheader_doc_tipo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='ek_pdf_file',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_xml_file',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_xml_file_signed',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
