# Generated by Django 3.2.22 on 2024-07-31 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0023_auto_20240731_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='ek_qr_img',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_transacion',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
