# Generated by Django 3.2.22 on 2024-08-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0024_auto_20240731_0502'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_redondeo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
    ]
