# Generated by Django 3.2.22 on 2024-08-10 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0025_documentheader_doc_redondeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoPagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('ext_link', models.BigIntegerField(default=0)),
                ('tipo_cod', models.IntegerField()),
                ('tipo', models.CharField(max_length=120)),
                ('tarjeta_denominacion_cod', models.IntegerField(null=True)),
                ('tarjeta_denominacion', models.CharField(max_length=120, null=True)),
                ('tarjeta_procesadora', models.CharField(max_length=120, null=True)),
                ('tarjeta_procesadora_ruc', models.CharField(max_length=120, null=True)),
                ('tarjeta_procesadora_ruc_dv', models.IntegerField(null=True)),
                ('tarjeta_procesamiento', models.IntegerField(null=True)),
                ('tarjeta_autorizacion_cod', models.IntegerField(null=True)),
                ('tarjeta_titular', models.CharField(max_length=200, null=True)),
                ('tarjeta_numero', models.IntegerField(null=True)),
                ('cheque_numero', models.CharField(max_length=12, null=True)),
                ('cheque_emisor', models.CharField(max_length=200, null=True)),
                ('monto', models.DecimalField(decimal_places=6, max_digits=19)),
                ('cargado_fecha', models.DateTimeField(null=True)),
                ('cargado_usuario', models.CharField(max_length=120, null=True)),
                ('documentheaderobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sifen.documentheader')),
            ],
        ),
    ]
