# Generated by Django 3.2.22 on 2024-08-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0026_documentopagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentopagos',
            name='tarjeta_autorizacion_cod',
            field=models.BigIntegerField(null=True),
        ),
    ]
