# Generated by Django 3.2.22 on 2024-08-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0027_alter_documentopagos_tarjeta_autorizacion_cod'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='cargado_fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='cargado_usuario',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
