# Generated by Django 3.2.22 on 2024-08-18 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0028_auto_20240818_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='cargado_fecha',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='cargado_usuario',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
