# Generated by Django 3.2.22 on 2024-08-18 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0029_auto_20240818_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='ek_xml_ekua',
            field=models.BooleanField(default=False),
        ),
    ]
