# Generated by Django 3.2.22 on 2024-08-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0030_alter_documentheader_ek_xml_ekua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdetail',
            name='prod_pais_origen',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
