# Generated by Django 3.2.22 on 2024-08-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0031_alter_documentdetail_prod_pais_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_establecimiento_ciudad',
            field=models.CharField(default='ASUNCIÓN', max_length=130),
        ),
    ]
