# Generated by Django 3.2.22 on 2024-08-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0032_documentheader_doc_establecimiento_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='ek_pdf_file',
            field=models.FileField(null=True, upload_to='invoice'),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_qr_img',
            field=models.FileField(null=True, upload_to='invoice'),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_xml_file',
            field=models.FileField(null=True, upload_to='invoice'),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_xml_file_signed',
            field=models.FileField(null=True, upload_to='invoice'),
        ),
    ]
