# Generated by Django 3.2.22 on 2024-08-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0033_auto_20240822_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdetail',
            name='cantidad',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_pdf_file',
            field=models.FileField(max_length=500, null=True, upload_to='invoice'),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_qr_img',
            field=models.FileField(max_length=500, null=True, upload_to='invoice'),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ek_xml_file',
            field=models.FileField(max_length=500, null=True, upload_to='invoice'),
        ),
    ]
