# Generated by Django 3.2.22 on 2024-08-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0034_auto_20240824_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentdetail',
            name='cantidad',
            field=models.DecimalField(decimal_places=6, max_digits=19),
        ),
    ]
