# Generated by Django 3.2.22 on 2024-08-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0035_alter_documentdetail_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='enviado_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='enviado_cliente_fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
