# Generated by Django 3.2.22 on 2024-10-04 16:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0037_documentrecibo_documentrecibodetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecibodetail',
            name='prof_number',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
