# Generated by Django 3.2.22 on 2024-10-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0038_documentrecibodetail_prof_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecibo',
            name='pdf_file',
            field=models.FileField(max_length=300, null=True, upload_to=''),
        ),
    ]
