# Generated by Django 3.2.22 on 2024-10-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0039_documentrecibo_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecibo',
            name='doc_expedicion',
            field=models.IntegerField(default=0),
        ),
    ]
