# Generated by Django 3.2.22 on 2024-10-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0040_documentrecibo_doc_expedicion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='base_gravada_10',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='base_gravada_5',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='precio_unitario_source',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
