# Generated by Django 3.2.22 on 2024-10-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0041_auto_20241016_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_relacion_monto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
