# Generated by Django 3.2.22 on 2024-10-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0042_documentheader_doc_relacion_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_relacion_numero',
            field=models.BigIntegerField(default=0),
        ),
    ]
