# Generated by Django 3.2.22 on 2024-10-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0043_documentheader_doc_relacion_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_total_redondeo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
            preserve_default=False,
        ),
    ]
