# Generated by Django 3.2.22 on 2024-10-29 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0044_documentheader_doc_total_redondeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_motivo',
            field=models.CharField(default='VTA', max_length=120),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='doc_relacion_monto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='doc_total_redondeo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
    ]
