# Generated by Django 3.2.22 on 2024-10-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0045_auto_20241029_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='doc_relacion_saldo',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
    ]
