# Generated by Django 3.2.22 on 2024-10-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0046_documentheader_doc_relacion_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='af_ciudad_cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_ciudad_nombre',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_direccion',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_distrito_cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_distrito_nombre',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_doc_id',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_dpto_cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_dpto_nombre',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_nombrefantasia',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_nro_casa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_tdoc',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_tdoc_cod',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_vendedor',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='af_vendedor_cod',
            field=models.IntegerField(default=0),
        ),
    ]
