# Generated by Django 3.2.22 on 2024-11-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0047_auto_20241031_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Retenciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retencion_numero', models.BigIntegerField()),
                ('pdv_codigo', models.BigIntegerField(default=0)),
                ('pdv_ruc', models.CharField(max_length=120)),
                ('pdv_ruc_dv', models.IntegerField(default=0)),
                ('pdv_nombrefantasia', models.CharField(max_length=300)),
                ('pdv_nombrefactura', models.CharField(max_length=300)),
                ('retencion', models.DecimalField(decimal_places=6, max_digits=19)),
                ('cargado_fecha', models.DateTimeField(null=True)),
                ('cargado_usuario', models.CharField(max_length=120, null=True)),
                ('anulado_usuario', models.CharField(max_length=120, null=True)),
                ('anulado_fecha', models.DateTimeField(blank=True, null=True)),
                ('actualizado_usuario', models.CharField(max_length=120, null=True)),
                ('actualizado_fecha', models.DateTimeField(blank=True, null=True)),
                ('enviado_cliente', models.BooleanField(default=False)),
                ('enviado_cliente_fecha', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
