# Generated by Django 3.2.22 on 2024-11-06 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0048_retenciones'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Retenciones',
            new_name='Retencion',
        ),
    ]
