# Generated by Django 3.2.22 on 2024-11-06 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0049_rename_retenciones_retencion'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='retencionobj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sifen.retencion'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='retencion_fecha',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
    ]
