# Generated by Django 3.2.22 on 2024-11-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0050_auto_20241106_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retencion',
            name='enviado_cliente',
        ),
        migrations.RemoveField(
            model_name='retencion',
            name='enviado_cliente_fecha',
        ),
    ]
