# Generated by Django 3.2.22 on 2024-11-07 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0051_auto_20241106_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retencion',
            name='retencion_fecha',
        ),
    ]
