# Generated by Django 3.2.22 on 2024-11-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0052_remove_retencion_retencion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='retencion_fecha',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
