# Generated by Django 3.2.22 on 2024-11-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0053_retencion_retencion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='prof_number',
            field=models.UUIDField(null=True),
        ),
    ]
