# Generated by Django 3.2.22 on 2024-11-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0054_retencion_prof_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retencion',
            name='prof_number',
        ),
        migrations.AddField(
            model_name='retencion',
            name='doc_loop_link',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='retencion',
            name='doc_relacion_monto',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='retencion',
            name='doc_relacion_numero',
            field=models.BigIntegerField(default=0),
        ),
    ]
