# Generated by Django 3.2.22 on 2024-11-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0055_auto_20241107_0447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retencion',
            name='doc_loop_link',
        ),
    ]
