# Generated by Django 3.2.22 on 2024-11-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0056_remove_retencion_doc_loop_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencion',
            name='doc_loop_link',
            field=models.IntegerField(null=True),
        ),
    ]
