# Generated by Django 3.2.22 on 2024-11-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0057_retencion_doc_loop_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='anulado_tipo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
