# Generated by Django 3.2.22 on 2024-12-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0058_documentheader_anulado_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecibodetail',
            name='retencion',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentrecibodetail',
            name='retencion_numero',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
