# Generated by Django 3.2.22 on 2025-04-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0059_auto_20241201_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='pcalc_result',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='pcalc_source',
            field=models.JSONField(default=dict),
        ),
    ]
