# Generated by Django 3.2.22 on 2025-04-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0060_auto_20250404_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='prod_autocreado',
            field=models.BooleanField(default=False),
        ),
    ]
