# Generated by Django 3.2.22 on 2025-05-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0061_documentdetail_prod_autocreado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='forma_pago',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='documentheader',
            name='forma_pago_id',
            field=models.IntegerField(default=0),
        ),
    ]
