# Generated by Django 3.2.22 on 2025-05-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0062_auto_20250528_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='forma_pago_id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
