# Generated by Django 5.2.8 on 2025-11-13 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0063_alter_documentheader_forma_pago_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('clientecodigo', models.AutoField(primary_key=True, serialize=False)),
                ('clientenombre', models.CharField(max_length=150)),
                ('clienteapellido', models.CharField(max_length=150)),
                ('clienteci', models.CharField(blank=True, max_length=30, null=True)),
                ('clientetelefono', models.CharField(blank=True, max_length=30, null=True)),
                ('clientecelular', models.CharField(blank=True, max_length=30, null=True)),
                ('clientemail', models.CharField(blank=True, max_length=150, null=True)),
                ('clientedireccion', models.CharField(blank=True, max_length=200, null=True)),
                ('ruc', models.CharField(blank=True, max_length=30, null=True)),
                ('ruc_dv', models.IntegerField(blank=True, default=0, null=True)),
                ('tipo_documento', models.CharField(choices=[('1', 'Cédula paraguaya'), ('2', 'Pasaporte'), ('3', 'Cédula extranjera'), ('4', 'Innominado'), ('5', 'Carnet de residencia'), ('9', 'Otro')], default='1', max_length=1)),
                ('clientefecharegistro', models.DateField(auto_now_add=True)),
                ('estado', models.BooleanField(default=True)),
                ('cargado_usuario', models.CharField(max_length=120, null=True)),
                ('cargado_fecha', models.DateTimeField(auto_now_add=True)),
                ('actualizado_usuario', models.CharField(max_length=120, null=True)),
                ('actualizado_fecha', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['clientenombre', 'clienteapellido'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('abreviatura', models.CharField(max_length=10)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PorcentajeIva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje', models.IntegerField()),
                ('descripcion', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_cod', models.BigIntegerField(unique=True)),
                ('descripcion', models.CharField(max_length=300)),
                ('ean', models.CharField(blank=True, max_length=300, null=True)),
                ('moneda', models.CharField(default='PYG', max_length=4)),
                ('precio', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('exenta', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('g5', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('g10', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('costo', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('stock', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('activo', models.BooleanField(default=True)),
                ('cargado_usuario', models.CharField(max_length=120, null=True)),
                ('cargado_fecha', models.DateTimeField(auto_now_add=True, null=True)),
                ('actualizado_usuario', models.CharField(max_length=120, null=True)),
                ('actualizado_fecha', models.DateTimeField(auto_now=True, null=True)),
                ('categoriaobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sifen.categoria')),
                ('marcaobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sifen.marca')),
                ('medidaobj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sifen.medida')),
                ('porcentaje_iva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sifen.porcentajeiva')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['descripcion'],
            },
        ),
    ]
