# Generated by Django 5.2.8 on 2025-11-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0064_categoria_clientes_marca_medida_porcentajeiva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(default='BCP', max_length=10)),
                ('moneda', models.CharField(default='PYG', max_length=4)),
                ('tasa_cambio', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('compra', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('venta', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodosPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
