# Generated by Django 5.2.8 on 2025-11-17 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0065_cotizacion_metodospago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
