# Generated by Django 5.2.8 on 2025-11-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0066_delete_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdv_innominado', models.BooleanField(default=False)),
                ('pdv_pais_cod', models.CharField(max_length=10, null=True)),
                ('pdv_pais', models.CharField(max_length=10, null=True)),
                ('pdv_tipocontribuyente', models.CharField(max_length=120, null=True)),
                ('pdv_es_contribuyente', models.BooleanField(default=True)),
                ('pdv_type_business', models.CharField(default='B2B', max_length=120, null=True)),
                ('pdv_codigo', models.BigIntegerField(default=0)),
                ('pdv_ruc', models.CharField(max_length=120)),
                ('pdv_ruc_dv', models.IntegerField(default=0)),
                ('pdv_nombrefantasia', models.CharField(max_length=300)),
                ('pdv_nombrefactura', models.CharField(max_length=300)),
                ('pdv_direccion_entrega', models.CharField(max_length=200, null=True)),
                ('pdv_dir_calle_sec', models.CharField(max_length=200, null=True)),
                ('pdv_direccion_comple', models.CharField(max_length=200, null=True)),
                ('pdv_numero_casa', models.IntegerField(default=0)),
                ('pdv_numero_casa_entrega', models.IntegerField(default=0)),
                ('pdv_dpto_cod', models.IntegerField(default=0)),
                ('pdv_dpto_nombre', models.CharField(max_length=200, null=True)),
                ('pdv_distrito_cod', models.IntegerField(default=0)),
                ('pdv_distrito_nombre', models.CharField(max_length=200, null=True)),
                ('pdv_ciudad_cod', models.IntegerField(default=0)),
                ('pdv_ciudad_nombre', models.CharField(max_length=200, null=True)),
                ('pdv_telefono', models.CharField(max_length=30, null=True)),
                ('pdv_celular', models.CharField(max_length=30, null=True)),
                ('pdv_email', models.CharField(max_length=120, null=True)),
            ],
        ),
    ]
