# Generated by Django 5.2.8 on 2025-11-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0067_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='pdv_ruc_estado',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
