# Generated by Django 5.2.8 on 2025-11-18 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0068_clientes_pdv_ruc_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medida',
            name='abreviatura',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='medida',
            name='nombre',
        ),
        migrations.AddField(
            model_name='medida',
            name='medida',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='medida_cod',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medida',
            name='medida_descripcion',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
