# Generated by Django 5.2.8 on 2025-11-22 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0069_remove_medida_abreviatura_remove_medida_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='lote',
            field=models.BigIntegerField(default=0),
        ),
    ]
