# Generated by Django 5.2.8 on 2025-11-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0071_documentheader_lote_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentheader',
            name='lote_estado',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
