# Generated by Django 5.2.8 on 2025-11-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0072_documentheader_lote_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapmsg',
            name='cdc',
            field=models.CharField(max_length=90, null=True),
        ),
    ]
