# Generated by Django 5.2.8 on 2025-11-22 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0073_alter_soapmsg_cdc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soapmsg',
            name='cdc',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
