# Generated by Django 5.2.8 on 2025-11-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0074_alter_soapmsg_cdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.FileField(max_length=500, null=True, upload_to='business'),
        ),
    ]
