# Generated by Django 5.2.8 on 2025-11-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0075_business_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetail',
            name='exenta_pct',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='g10_pct',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='documentdetail',
            name='g5_pct',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
    ]
