# Generated by Django 5.2.8 on 2025-11-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0076_documentdetail_exenta_pct_documentdetail_g10_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='photo',
            field=models.ImageField(max_length=300, null=True, upload_to='products/'),
        ),
    ]
