# Generated by Django 5.2.8 on 2025-11-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0077_producto_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='web',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
