# Generated by Django 5.2.8 on 2025-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0078_business_web'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='pdv_type_business',
            field=models.CharField(default='B2C', max_length=120, null=True),
        ),
    ]
