# Generated by Django 5.2.8 on 2025-12-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0079_alter_clientes_pdv_type_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='cargado_fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cargado_usuario',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='ext_link',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
