# Generated by Django 5.2.8 on 2026-01-05 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0080_clientes_cargado_fecha_clientes_cargado_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del certificado (ej: Certificado SIFEN 2024)', max_length=200)),
                ('pfx_file', models.FileField(help_text='Archivo de certificado en formato PFX/P12', max_length=500, upload_to='certificates/pfx/')),
                ('pfx_password_encrypted', models.TextField(help_text='Contraseña del certificado PFX (encriptada)')),
                ('pem_file', models.FileField(blank=True, help_text='Archivo PEM generado (certificado)', max_length=500, null=True, upload_to='certificates/pem/')),
                ('key_file', models.FileField(blank=True, help_text='Archivo KEY generado (clave privada)', max_length=500, null=True, upload_to='certificates/key/')),
                ('titular', models.CharField(blank=True, help_text='Titular del certificado (CN del subject)', max_length=300, null=True)),
                ('emisor', models.CharField(blank=True, help_text='Autoridad emisora del certificado', max_length=300, null=True)),
                ('numero_serie', models.CharField(blank=True, help_text='Número de serie del certificado', max_length=100, null=True)),
                ('fecha_emision', models.DateTimeField(blank=True, help_text='Fecha de emisión del certificado', null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha de vencimiento del certificado', null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Procesar'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('error', 'Error al Procesar'), ('revocado', 'Revocado')], default='pendiente', help_text='Estado actual del certificado', max_length=20)),
                ('es_predeterminado', models.BooleanField(default=False, help_text='Indica si es el certificado predeterminado para la empresa')),
                ('ultimo_uso', models.DateTimeField(blank=True, help_text='Última vez que se usó para firmar un documento', null=True)),
                ('documentos_firmados', models.IntegerField(default=0, help_text='Contador de documentos firmados con este certificado')),
                ('error_mensaje', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló', null=True)),
                ('cargado_fecha', models.DateTimeField(auto_now_add=True)),
                ('cargado_usuario', models.CharField(max_length=120, null=True)),
                ('actualizado_fecha', models.DateTimeField(auto_now=True)),
                ('actualizado_usuario', models.CharField(max_length=120, null=True)),
                ('businessobj', models.ForeignKey(help_text='Empresa a la que pertenece el certificado', on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='Sifen.business')),
            ],
            options={
                'verbose_name': 'Certificado Digital',
                'verbose_name_plural': 'Certificados Digitales',
                'ordering': ['-es_predeterminado', '-cargado_fecha'],
            },
        ),
    ]
