# Generated by Django 5.2.8 on 2026-01-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0081_certificate_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='css_invoice',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='business/css'),
        ),
        migrations.AddField(
            model_name='business',
            name='css_invoice_content',
            field=models.TextField(blank=True, help_text='Contenido CSS para facturas (se auto-genera del archivo)', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='favicon',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='business/favicon'),
        ),
        migrations.AddField(
            model_name='business',
            name='logo_invoice',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='business/invoice'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pfx_file',
            field=models.FileField(help_text='Archivo de certificado PKCS#12 (.p12 o .pfx)', max_length=500, upload_to='certificates/pfx/'),
        ),
    ]
