# Generated by Django 5.2.8 on 2026-01-11 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0082_business_branding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='anclaje_cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
