# Generated by Django 5.2.8 on 2026-03-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0083_add_anclaje_cliente_to_clientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='doc_por_ws',
            field=models.BooleanField(default=False),
        ),
    ]
