# Generated by Django 5.2.8 on 2026-07-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sifen', '0084_clientes_doc_por_ws'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrecibo',
            name='doc_tarjeta',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='documentrecibo',
            name='doc_transferencia',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='documentheader',
            name='pdv_type_business',
            field=models.CharField(default='B2C', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='documentrecibo',
            name='pdv_type_business',
            field=models.CharField(default='B2C', max_length=120, null=True),
        ),
    ]
