# Generated by Django 5.2.8 on 2025-11-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FailedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=125)),
                ('full_name', models.TextField()),
                ('args', models.TextField(blank=True, null=True)),
                ('kwargs', models.TextField(blank=True, null=True)),
                ('exception_class', models.TextField()),
                ('exception_msg', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(max_length=36)),
                ('failures', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Printers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('uri', models.CharField(max_length=120)),
                ('port', models.CharField(max_length=120)),
                ('user', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('save_user', models.CharField(max_length=120)),
                ('date_save', models.DateTimeField()),
                ('delete_user', models.CharField(max_length=120, null=True)),
                ('date_delete', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SysParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=120)),
                ('tipo', models.CharField(max_length=60)),
                ('valor_s', models.TextField()),
                ('valor_f', models.FloatField()),
                ('valor_j', models.JSONField(default=dict)),
                ('ruta_archivo', models.FileField(null=True, upload_to='opts')),
                ('vigencia', models.DateField()),
                ('save_user', models.CharField(max_length=120)),
                ('date_save', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackBtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('username', models.CharField(max_length=80, null=True)),
                ('module', models.CharField(max_length=80, null=True)),
                ('package', models.CharField(max_length=80, null=True)),
                ('attr', models.CharField(max_length=80, null=True)),
                ('mname', models.CharField(max_length=80, null=True)),
                ('args', models.TextField(null=True)),
                ('kwargs', models.TextField(null=True)),
                ('state', models.CharField(max_length=80, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
