# Generated by Django 5.2.8 on 2025-11-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptsIO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(default=0)),
                ('menu', models.CharField(max_length=80)),
                ('app_name', models.CharField(max_length=80, unique=True)),
                ('friendly_name', models.CharField(max_length=120)),
                ('icon', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=20)),
                ('background', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(default=0)),
                ('menu', models.CharField(max_length=80)),
                ('friendly_name', models.CharField(max_length=120)),
                ('icon', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('background', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppsBookMakrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(default=0)),
                ('username', models.CharField(max_length=80)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='OptsIO.apps')),
            ],
            options={
                'db_table': 'apps_man_appsbookmarks',
                'unique_together': {('app', 'username')},
            },
        ),
    ]
