# Generated by Django 5.2.8 on 2025-11-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptsIO', '0002_apps_menu_appsbookmakrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, max_length=80)),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField(default='Starting...')),
                ('progress', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='processing', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['username', 'status'], name='OptsIO_user_usernam_6c7991_idx')],
            },
        ),
    ]
