# Generated by Django 5.2.8 on 2025-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptsIO', '0003_usertask_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='apps',
            name='menu_icon',
            field=models.CharField(default='mdi mdi-folder-outline', max_length=200),
        ),
    ]
