# Generated by Django 5.2.8 on 2025-11-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptsIO', '0004_apps_menu_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertask',
            name='dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
