# Generated by Django 5.2.8 on 2025-11-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptsIO', '0005_usertask_dismissed'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80, unique=True)),
                ('preferences', models.JSONField(default=dict)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/')),
                ('last_change_password', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
