# Generated by Django 5.2.8 on 2025-11-22 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptsIO', '0006_userprofile'),
        ('Sifen', '0075_business_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('businessobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sifen.business')),
                ('userprofileobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptsIO.userprofile')),
            ],
        ),
    ]
