# Generated by Django 5.2.8 on 2026-01-04 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptsIO', '0007_userbusiness'),
        ('Sifen', '0080_clientes_cargado_fecha_clientes_cargado_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre único del plugin', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Nombre para mostrar', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción del plugin')),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('app_name', models.CharField(help_text='Nombre de la app Django asociada', max_length=100)),
                ('module_path', models.CharField(help_text='Path al módulo del plugin', max_length=200)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('error', 'Error')], default='inactive', max_length=20)),
                ('is_core', models.BooleanField(default=False, help_text='Si es un plugin core (no se puede desactivar)')),
                ('dependencies', models.JSONField(blank=True, default=list)),
                ('icon', models.CharField(default='mdi mdi-puzzle', max_length=100)),
                ('category', models.CharField(default='general', max_length=50)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceDataLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_type', models.CharField(choices=[('geografias', 'Geografías'), ('actividades', 'Actividades Económicas'), ('medidas', 'Unidades de Medida'), ('tipo_contribuyente', 'Tipos de Contribuyente'), ('porcentaje_iva', 'Porcentajes IVA'), ('metodos_pago', 'Métodos de Pago'), ('custom', 'Personalizado')], max_length=50)),
                ('source_file', models.CharField(blank=True, max_length=255)),
                ('source_hash', models.CharField(blank=True, help_text='Hash del archivo fuente', max_length=64)),
                ('records_loaded', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_skipped', models.IntegerField(default=0)),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('loaded_by', models.CharField(blank=True, max_length=80)),
                ('version', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-loaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPlugin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_by', models.CharField(blank=True, max_length=80)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sifen.business')),
                ('plugin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OptsIO.plugin')),
            ],
            options={
                'ordering': ['plugin__category', 'plugin__name'],
                'unique_together': {('business', 'plugin')},
            },
        ),
        migrations.CreateModel(
            name='SetupStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('running', 'Ejecutando'), ('completed', 'Completado'), ('error', 'Error'), ('skipped', 'Omitido')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_by', models.CharField(blank=True, max_length=80)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sifen.business')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('name', 'business')},
            },
        ),
    ]
