# Generated by Django 5.2.8 on 2026-01-11 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OptsIO', '0008_plugin_system'),
        ('Sifen', '0082_business_branding_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre del rol (ej: Administrador, Vendedor)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del rol')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('businessobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='Sifen.business')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'optsio_roles',
                'ordering': ['businessobj', 'name'],
                'unique_together': {('name', 'businessobj')},
            },
        ),
        migrations.CreateModel(
            name='RolesApps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appsobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_roles', to='OptsIO.apps')),
                ('businessobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_role_apps', to='Sifen.business')),
                ('rolesobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_apps', to='OptsIO.roles')),
            ],
            options={
                'verbose_name': 'Rol de Aplicación',
                'verbose_name_plural': 'Roles de Aplicaciones',
                'db_table': 'optsio_roles_apps',
                'ordering': ['businessobj', 'rolesobj', 'appsobj'],
                'unique_together': {('rolesobj', 'appsobj', 'businessobj')},
            },
        ),
        migrations.CreateModel(
            name='RolesUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('businessobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_user_roles', to='Sifen.business')),
                ('rolesobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='OptsIO.roles')),
                ('userprofileobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='OptsIO.userprofile')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'optsio_roles_user',
                'ordering': ['businessobj', 'userprofileobj'],
                'unique_together': {('userprofileobj', 'rolesobj', 'businessobj')},
            },
        ),
    ]
