# Generated by Django 5.2.8 on 2025-11-16 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='animeobj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Anime.anime'),
        ),
    ]
