# Generated by Django 5.2.8 on 2026-03-21 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OptsIO', '0009_roles_rolesapps_rolesuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFLSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.IntegerField()),
                ('userprofileobj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fl_sucursales', to='OptsIO.userprofile')),
            ],
            options={
                'verbose_name': 'Sucursal FL por Usuario',
                'verbose_name_plural': 'Sucursales FL por Usuario',
                'unique_together': {('userprofileobj', 'sucursal')},
            },
        ),
    ]
