import json

ff = [
    "ReclamoTrazabilidadUi -> reclamoheaderobj_id",
    "ReclamoTrazabilidadUi -> accion_id",
    "ReclamoTrazabilidadUi -> comentario",
    "ReclamoTrazabilidadUi -> documento",
    
    "ReclamoAccionCreateUi -> orden",
    "ReclamoAccionCreateUi -> accion",
    
    "ReclamoCreateUi -> topico_id",
    "ReclamoCreateUi -> clientecodigo",
    "ReclamoCreateUi -> asignado",
    "ReclamoCreateUi -> identificador",
    "ReclamoCreateUi -> valor",
    "ReclamoCreateUi -> estado",
    "ReclamoCreateUi -> descripcion",
    
    "ReclamoSolucionCreateUi -> orden",
    "ReclamoSolucionCreateUi -> solucion",
    "ReclamoSolucionCreateUi -> requiere_intervencion",
    
    "ReclamoTopicoCreateUi -> topico",
    
    "UserProfileUi -> foto",
    "UserProfileUi -> funcionariocorreo",
    "UserProfileUi -> funcionariocelular",
    "UserProfileUi -> funcionariotel",
    "UserProfileUi -> funcionariodireccion",
    "UserProfileUi -> funcionariopassword",
    "UserProfileUi -> funcionariopassword2",

    "UserCreateUi -> funcionarioci",
    "UserCreateUi -> funcionarionombre",
    "UserCreateUi -> funcionarioapellido",
    "UserCreateUi -> funcionariocorreo",
    "UserCreateUi -> funcionariotel",
    "UserCreateUi -> funcionariocelular",
    "UserCreateUi -> funcionariodireccion",
    "UserCreateUi -> ciudad",
    "UserCreateUi -> sucursal",
    "UserCreateUi -> codoficina",
    "UserCreateUi -> codigorol",
    "UserCreateUi -> cargocodigo",
    "UserCreateUi -> tipopanel",
    "UserCreateUi -> funcionariopassword",
    "UserCreateUi -> funcionariopassword2",
    "UserCreateUi -> funcionarioestado",
    "UserCreateUi -> inactive_screen",
    "UserCreateUi -> password_timechange",
    "UserCreateUi -> first_login",
    
    "SegmentoCrearUi -> segmento",
    
    "PorcentajeivaCrearUi -> descripcion",
    "PorcentajeivaCrearUi -> porcentaje",

    "OficinaRemotaCrearUi -> nomoficina",
    "OficinaRemotaCrearUi -> razon_social",
    "OficinaRemotaCrearUi -> pais",
    "OficinaRemotaCrearUi -> pais_icono",
    "OficinaRemotaCrearUi -> ciudad",
    "OficinaRemotaCrearUi -> encargado",
    "OficinaRemotaCrearUi -> modalidad",
    "OficinaRemotaCrearUi -> modalidad_icono",
    "OficinaRemotaCrearUi -> modalidad_imagen",
    "OficinaRemotaCrearUi -> telefono",
    "OficinaRemotaCrearUi -> peso_minimo",
    "OficinaRemotaCrearUi -> direccion",
    "OficinaRemotaCrearUi -> tere_paistrans",
    "OficinaRemotaCrearUi -> tere_paismedtrans",
    "OficinaRemotaCrearUi -> estado",
    "OficinaRemotaCrearUi -> colortxt",
    "OficinaRemotaCrearUi -> colorbgnd",
    
    "ProductoCrearUi -> descripcion",
    "ProductoCrearUi -> categoriaobj_id",
    "ProductoCrearUi -> porcentaje_iva_id",
    "ProductoCrearUi -> medidaobj_id",
    "ProductoCrearUi -> moneda",
    "ProductoCrearUi -> exenta",
    "ProductoCrearUi -> g5",
    "ProductoCrearUi -> g10",
    "ProductoCrearUi -> precio",
    
    "CategoriaCrearUi -> categoria",
    
    "MarcaCrearUi -> marca",
    
    "MedidaCrearUi -> medida_cod",
    "MedidaCrearUi -> medida",

    "SucursalCrearUi -> nombre",
    "SucursalCrearUi -> codigoalfanumerico",
    "SucursalCrearUi -> nempresa",
    "SucursalCrearUi -> ruc",
    "SucursalCrearUi -> abv",
    "SucursalCrearUi -> website",
    "SucursalCrearUi -> pais",
    "SucursalCrearUi -> ciudad",
    "SucursalCrearUi -> encargado",
    "SucursalCrearUi -> nomencargado",
    "SucursalCrearUi -> telefono",
    "SucursalCrearUi -> email",
    "SucursalCrearUi -> direccion",
    "SucursalCrearUi -> colortxt",
    "SucursalCrearUi -> colorbgnd",
    "SucursalCrearUi -> foto",
    "SucursalCrearUi -> latitud",
    "SucursalCrearUi -> longitud",
    
    "WstereCiaAereaCrearUi -> code",
    "WstereCiaAereaCrearUi -> description",
    
    "DeliveryZoneCrearUi -> nombre",
    "DeliveryZoneCrearUi -> costo",
    "DeliveryZoneCrearUi -> deliveryzonedetail_id",
    "DeliveryZoneCrearUi -> ciudad",

    "PartidasArancelariasCrearUi -> codigo",
    "PartidasArancelariasCrearUi -> descripcion",
    "PartidasArancelariasCrearUi -> partida",

    "OrderCrearUi -> clientecodigo",
    "OrderCrearUi -> forma_pago",
    "OrderCrearUi -> modalidad",
    "OrderCrearUi -> tasa_cambio",
    "OrderCrearUi -> feed_percentage",
    "OrderCrearUi -> moneda",
    "OrderCrearUi -> orderdetail_id",
    "OrderCrearUi -> paquetedescripcion",
    "OrderCrearUi -> paqueteremitente",
    "OrderCrearUi -> link_producto",
    "OrderCrearUi -> paqueteprecio",
    "OrderCrearUi -> observacion",
    "OrderCrearUi -> procesado_usuario",
    "OrderCrearUi -> cobrado_usuario",

    "ReceptionFormUi -> paquetecodigo",
    "ReceptionFormUi -> embarquecodigo",
    "ReceptionFormUi -> paquetetracking",
    "ReceptionFormUi -> estante",
    "ReceptionFormUi -> fechallegada",
    "ReceptionFormUi -> client_suite",
    "ReceptionFormUi -> sucursal",
    "ReceptionFormUi -> cliente",
    "ReceptionFormUi -> paqueteobservacion",
    
    "EPrecioCrearUi -> zona",
    "EPrecioCrearUi -> peso_a",
    "EPrecioCrearUi -> peso_b",
    "EPrecioCrearUi -> precio",
    "EPrecioCrearUi -> exenta",
    "EPrecioCrearUi -> g5",
    "EPrecioCrearUi -> g10",
    
    "EnvioCrearUi -> clientecodigo",
    "EnvioCrearUi -> peso",
    "EnvioCrearUi -> zona",
    "EnvioCrearUi -> largo",
    "EnvioCrearUi -> alto",
    "EnvioCrearUi -> ancho",
    "EnvioCrearUi -> peso_calculado",
    "EnvioCrearUi -> precio",
    "EnvioCrearUi -> peso_elegido",
    "EnvioCrearUi -> precio_civa",
    "EnvioCrearUi -> precio_gs",
    "EnvioCrearUi -> precio_gs_civa",
    "EnvioCrearUi -> paquetetracking",
    "EnvioCrearUi -> paquetedescripcion",
    "EnvioCrearUi -> archcomercial_full",
    "EnvioCrearUi -> deslinde_full",
    
    "RetencionCreateUi -> pdv_codigo",
    "RetencionCreateUi -> pdv_ruc",
    "RetencionCreateUi -> pdv_ruc_dv",
    "RetencionCreateUi -> pdv_nombrefactura",
    "RetencionCreateUi -> retencion_fecha",
    "RetencionCreateUi -> retencion_numero",
    "RetencionCreateUi -> doc_loop_link",
    "RetencionCreateUi -> retencion",
    
    "DocumentHeaderCreateUi -> pdv_codigo",
    "DocumentHeaderCreateUi -> pdv_ruc",
    "DocumentHeaderCreateUi -> pdv_ruc_dv",
    "DocumentHeaderCreateUi -> pdv_email",
    "DocumentHeaderCreateUi -> pdv_direccion_entrega",
    "DocumentHeaderCreateUi -> pdv_nombrefactura",
    "DocumentHeaderCreateUi -> doc_cre_tipo_cod",
    "DocumentHeaderCreateUi -> doc_moneda",
    "DocumentHeaderCreateUi -> doc_fecha",
    "DocumentHeaderCreateUi -> doc_tipo",
    "DocumentHeaderCreateUi -> doc_numero",
    "DocumentHeaderCreateUi -> doc_vencimiento",
    "DocumentHeaderCreateUi -> tasa_cambio",
    "DocumentHeaderCreateUi -> doc_relacion_cdc",
    "DocumentHeaderCreateUi -> doc_motivo",
    "DocumentHeaderCreateUi -> af_vendedor_cod",
    "DocumentHeaderCreateUi -> af_tdoc_cod",
    "DocumentHeaderCreateUi -> af_doc_id",
    "DocumentHeaderCreateUi -> af_nombrefantasia",
    "DocumentHeaderCreateUi -> af_direccion",
    "DocumentHeaderCreateUi -> af_dpto_cod",
    "DocumentHeaderCreateUi -> af_distrito_cod",
    "DocumentHeaderCreateUi -> af_ciudad_cod",
    "DocumentHeaderCreateUi -> documentdetail_id",
    "DocumentHeaderCreateUi -> prod_cod",
    "DocumentHeaderCreateUi -> prod_cod",
    "DocumentHeaderCreateUi -> precio_unitario",
    "DocumentHeaderCreateUi -> cantidad",
    "DocumentHeaderCreateUi -> d_total",
    "DocumentHeaderCreateUi -> observacion",
    
    "PosCrearUi -> nombre",
    "PosCrearUi -> ip_address",
    
    "ClienteCategoriaUpdateUi -> categoriaobj_id",
    "ClienteCategoriaUpdateUi -> tarifa",

    "ClienteCategoriaCreateUi -> categoriaobj_id",
    "ClienteCategoriaCreateUi -> ofremotaobj_id",
    "ClienteCategoriaCreateUi -> tarifa",
    
    "ValidarClienteUi -> clientecodigo",
    "ValidarClienteUi -> ruc",
    "ValidarClienteUi -> dv",
    "ValidarClienteUi -> nombrefactura",
    "ValidarClienteUi -> forma_pago",
    "ValidarClienteUi -> telefono",
    "ValidarClienteUi -> email",
    "ValidarClienteUi -> ciudad_cod",
    "ValidarClienteUi -> direccion",
    "ValidarClienteUi -> numero_casa",

    "PaqueteRetenidoCreateUi -> clientecodigo",
    "PaqueteRetenidoCreateUi -> motivo",
    "PaqueteRetenidoCreateUi -> estante",
    "PaqueteRetenidoCreateUi -> paquetetracking",
    "PaqueteRetenidoCreateUi -> paquetedescripcion",
    "PaqueteRetenidoCreateUi -> paquetefoto",
    "PaqueteRetenidoCreateUi -> paquetepeso",
    "PaqueteRetenidoCreateUi -> paquetelargo",
    "PaqueteRetenidoCreateUi -> paquetealto",
    "PaqueteRetenidoCreateUi -> paqueteancho",
    "PaqueteRetenidoCreateUi -> paquetevolumen",
    "PaqueteRetenidoCreateUi -> paqueteremitente",
    "PaqueteRetenidoCreateUi -> paqueteobservacion",
    "PaqueteRetenidoCreateUi -> resuelto",
    
    "PaqueteDesconocidoCreateUi -> codoficina",
    "PaqueteDesconocidoCreateUi -> embarque",
    "PaqueteDesconocidoCreateUi -> clientecodigo",
    "PaqueteDesconocidoCreateUi -> estante",
    "PaqueteDesconocidoCreateUi -> paquetetracking",
    "PaqueteDesconocidoCreateUi -> paquetedescripcion",
    "PaqueteDesconocidoCreateUi -> paquetefoto",
    "PaqueteDesconocidoCreateUi -> paqueteremitente",
    "PaqueteDesconocidoCreateUi -> paquetepeso",
    "PaqueteDesconocidoCreateUi -> paquetelargo",
    "PaqueteDesconocidoCreateUi -> paquetealto",
    "PaqueteDesconocidoCreateUi -> paqueteancho",
    "PaqueteDesconocidoCreateUi -> paquetevolumen",
    "PaqueteDesconocidoCreateUi -> paqueteobservacion",
    "PaqueteDesconocidoCreateUi -> resuelto",
    "PaqueteDesconocidoSearchUi -> cargado_fecha",
    "PaqueteDesconocidoSearchUi -> cargado_fecha",
    "PaqueteDesconocidoSearchUi -> paquetedescripcion",
    "PaqueteDesconocidoSearchUi -> paquetepeso",
    "PaqueteDesconocidoSearchUi -> paquetepeso",
    "PaqueteDesconocidoSearchUi -> paqueteobservacion",
    
    "MotivoPaqueteRetenidoCrearUi -> motivo",
    "MotivoPaqueteRetenidoCrearUi -> tipo_retencion",

    "PaqueteDepositoDetailUi -> clientecodigo",
    "PaqueteDepositoDetailUi -> estante_actual",
    "PaqueteDepositoDetailUi -> estante",
]

form_structure = {}

for item in ff:
    form_name, field_name = item.split(" -> ")
    form_name = form_name.replace("ui", "").replace("UI", "").replace("Ui", "").replace("uI", "")
    form_key = f"FORMULARIO_{form_name.upper()}"

    if form_key not in form_structure:
        form_structure[form_key] = []

    form_structure[form_key].append(
        {
            "perm": f"form_{form_name.lower()}_{field_name.lower()}_ver",
            "pname": f"VER {field_name.upper()}",
            "gname": f"FORMULARIO {form_name.upper()}",
            "groups": [],
        }
    )

    form_structure[form_key].append(
        {
            "perm": f"form_{form_name.lower()}_{field_name.lower()}_edita",
            "pname": f"EDITA {field_name.upper()}",
            "gname": f"FORMULARIO {form_name.upper()}",
            "groups": [],
        }
    )

# print(form_structure)

with open("/tmp/perms.json", "w") as f:
    json.dump(form_structure, f, indent=4)
